// <auto-generated />
namespace ConsoleEmpApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class v2_balne : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v2_balne));
        
        string IMigrationMetadata.Id
        {
            get { return "202107310705059_v2_balne"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
